CREATE USER SETTEST;
CREATE SCHEMA "SETTEST" AUTHORIZATION "SETTEST"
	CREATE TABLE TABLE_1 (a integer)
	CREATE TABLE TABLE_2 (a integer)
;

COMMIT;

CONNECT TO 'THINKSQL' USER 'SETTEST';

INSERT INTO table_1 values (0),(1),(2),(2),(3);
INSERT INTO table_2 values (1),(2),(3),(5),(5);

COMMIT; 

SELECT * FROM table_1;
SELECT * FROM table_2;
